### ISSUE TITLE
Fix `F2` rename support.

### ISSUE THREAD

**Issue by ttax00** [TechTheAwesome/code-yew-server#1]
**Problem 1**:
When triggering rename symbol with `rust-analyzer` active:
![image](https://user-images.githubusercontent.com/10691398/199177800-44733907-8962-4e1f-99c7-a761feab259e.png)
Extension's `provideRenameEdits()` won't be triggered.  
```ts
async provideRenameEdits(document, position, newName, token, next) {
// If not in `html! {}`, do not perform request forwarding
if (!isInsideHTMLRegion(document.getText(), document.offsetAt(position))) {
	return await next(document, position, newName, token);
}
console.log("doing rename!");
// FIXME: [1] rust-analyzer's rename still take priority inside `html! {}` scope
// FIXME: [2] even when called on `<div></div> virtual document, returned unexpected type
const result = await commands.executeCommand<WorkspaceEdit>(
	'vscode.executeDocumentRenameProvider',
	vdocUri(document),
	position,
	newName
);
console.debug(result);
return result;
},
```

**Problem 2**:
When `rust-analyzer` is disabled. `vdocUri(document)` resolves to a virtual `.html` file that should work with `HTML Language Server`. But instead it returns with an unexpected type.  
![image](https://user-images.githubusercontent.com/10691398/199178474-df53a466-ead2-4847-98c0-f56bc5832283.png)
![image](https://user-images.githubusercontent.com/10691398/199178556-2eaaaa52-8cfd-4fa0-9e60-dce69016d108.png)
Content of the virtual `.html` document:
```html
                    \n
           \n
          \n
            <noscript>                                                  </noscript>\n
            \n
           \n
     \n
 \n
```
Expected behavior: `command.execute()` returns a `WorkspaceEdit` that's would rename `noscript` tag to `test`

**TODOS**:
1. [x] Solve priority issues with `rust-analyzer` so `middleman` injection gets called.
2. [ ] Solve `unexpected type` from calling `HTML Language Server` with `vscode.executeDocumentRenameProvider` command.

**Comment by allan2** [comment]
**When rust-analyzer is running**
F2 rename on an element causes an "inconsistent text range" error to appear in an overlay above the F2'ed element.

**When rust-analyzer is off**
F2 rename does nothing.

Is F2 rename supposed to be working with RA disabled?

//

Side note: [Auto Rename Tag](https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-rename-tag) has mirrored cursors for renaming open/close tags at the same time. I'm using it for Yew and JSX.

**Comment by ttax00** [comment]
> **When rust-analyzer is running** 
> **When rust-analyzer is off** F2 rename does nothing.

Sadly yes, rename support right now doesn't work, due to two main issues under **TODO** on the main post. 
When RA is off, HTML Language Server doesn't return a valid `WorkspaceEdit` object. And instead throws `Unexpected type` error. Which is put it mildly, unhelpful :sweat_smile: . The extension is basically passing most of the heavy work onto the `.html` parser built into vscode. So right now I couldn't do much but raising issues on their respective repositories, Unless you had some idea of what went wrong. 

> Side note: [Auto Rename Tag](https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-rename-tag) has mirrored cursors for renaming open/close tags at the same time. I'm using it for Yew and JSX.

Ok, this looks great, I'll take a look into it, but not sure if re-implementing it is the way, or just recommend the extension with some documentations. (If the extension expose an API, I can tap into that without re-implementing).
