### ISSUE TITLE
Big perfomance issue

### ISSUE THREAD

**Issue by lvaroqui** [TechTheAwesome/code-yew-server#3]
Hi,

Thanks for your extension! I just tried it and it seems it causes big performance issue on my setup. After some time all VS Code start to be slow. If I open the dev console with `Developer: Toggle Developer Tools`, I see this debug message is spammed:
```
[Extension Host] Map(1) {
  'embedded-content:///projects/test/src/lib.rs.html' => '                                                \n' +
    '                \n' +
    ' \n' +
    '\n' +
    '            \n' +
    '           \n' +
    '                 \n' +
    '\n' +
    '           \n' +
    '                   \n' +
    '                               \n' +
    '                              \n' +
    '     \n' +
    ' \n'
}
```
My lib.rs doesn't even contain an `html!` macro!

**Comment by ttax00** [comment]
Oops, those are the debug logs. Well I didn't remove them since it's not released yet, but I'm all ears if you have a suggestion on adding `production` & `development` environment to enable/disable such code.

**Comment by ttax00** [comment]
Oh wait, my mistake... I didn't think of no `html!` macro case and the while loop goes wild 😅
